version: '2.2'
services:

  artist-catalog:
    build: .
    container_name: artist-catalog
    ports:
      - "8080:8080"
    network_mode: host

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    network_mode: host
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  esdata1:
    driver: local
